services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASSWORD=password
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      - database
      

  database:
    image: postgres:15.6
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: